#!/bin/sh

export POSIXLY_CORRECT=yes
export LC_NUMERIC=en_US.UTF-8

print_help () 
{
  echo "Usage: tradelog [-h|--help]"
  echo "       tradelog [FILTETR...] [COMMAND] [LOG...]"
  echo "Command list:"
  echo "        list-tick - list of occurring stock symbols.
        profit - statement of total profit from closed positions.
        pos - list of values of currently held positions sorted in descending order by value.
        last-price - list of the last known price for each ticker.
        hist-ord - list of histogram of the number of transactions according to the ticker.
        graph-pos - list of graph of values of held positions according to the ticker."
  echo "Filter agruments:"
  echo "        -a DATETIME - after: only records after this date are considered. DATETIME is in the format YYYY-MM-DD HH: MM: SS.
        -b DATETIME - before: only records BEFORE this date are considered.
        -t TICKER - only records corresponding to the given ticker are considered.
        -w WIDTH - sets the width of the graph listing, ie the length of the longest line to WIDTH." 
}

COMMAND=""
AFTERTIME=""
BEFORETIME=""
LOG=""
GZ_LOG=""
TICKER=""
#promenna for tickers

#zpracovani argumentu
while [ "$#" -gt  0 ];  do #bezi, dokud mame nejake parametry
  case "$1" in
  list-tick | pos |profit | last-price |hist-ord |graph-pos )
    COMMAND="$1"
    shift
    ;;
  -h | --help )
    print_help
    exit 0
    ;;
  -w)
    WIDTH="$2"
    shift
    shift
    ;;
  -a)
    AFTERTIME="$2"
    shift
    shift
    ;;
  -b)
    BEFORETIME="$2" #pokud chci toto pouzit "$prom"
    shift
    shift
    ;;
  -t)
    TICKER="$2| $TICKER"
    shift
    shift
    ;;
  *.gz)
    GZ_LOG="$1"
    shift
    ;;
  *)
    LOG="$1"
    shift
    ;;
  esac
done

READ_INPUT=$(gzip -d -c -q $GZ_LOG | cat - $LOG)
#printf "%s\n" "$READ_FILTERED"
#UDELEJ FILTRACI

TICK_FILTER="grep '^.*\;$TICKER'"
READ_FILTERED="eval cat $READ_INPUT | sort -t ';' -k 2,2| awk -F ';' '{if ($1> "$AFTERTIME" && $1< "$BEFORETIME") print $0 }' | eval $TICKER)"



#TICK_FILTER="grep "$TICKER""
#TICK_FILTER="grep -E '^.*\;$TICKER'"



#READ_FILTERED="eval cat $READ_INPUT | awk -F ';' '{if ($1> "$AFTERTIME" && $1< "$BEFORETIME") print $0 }' | eval $TICK_FILTER"

#eval cat stock-1.log | sort | awk -F ';' '{if ($1 > "0000-01-01 00:00:00" && $1 < "9999-12-31 23:59:59" ) print $0 }' | eval cat
#eval cat stock-1.log | sort | awk -F ';' '{if ($1 > "0000-01-01 00:00:00" && $1 < "9999-12-31 23:59:59" ) print $0 }' | eval grep -E '^.*\;BTC'


#dej sem smycku: pokud mame prazdny COMMAND; prazdny TICKER atd, tak budes 
#jen vypisovat soubory na vystup, abecedne dle tickeru +




#podminka for command, pokud odpovida tak neco delej
#if []
  #eval "$READ_FILTERED |"
  #TODO
#fi 
